version: '3.8'

services:
  # Servicio de MySQL
  mysql-container:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mi_base_datos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - mi_red

  # Servicio de la aplicación Spring Boot
  app-container:
    build: .
    container_name: spring-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    networks:
      - mi_red

networks:
  mi_red:
